services:
  _instanceof:
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ['setContainer', ['@service_container']]
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Trilobit\HeaderfootercodeBundle\EventListener\ParseTemplateListener: ~
